image: blackstonegm/buildtools:latest

stages:
  - build

build:
  stage: build
  artifacts:
    paths:
      - "/builds/bs-studios/bsos-cpp/build/*"
  script:
    - cd kernel
    - make setup
    - cd ../gnu-efi
    - make bootloader
    - cd ../kernel
    - make kernel
    - make buildimg
    - mkdir /builds/bs-studios/bsos-cpp/build
    - mkdir /builds/bs-studios/bsos-cpp/build/kernel
    - mkdir /builds/bs-studios/bsos-cpp/build/OVMFbin
    - cp /builds/bs-studios/bsos-cpp/kernel/bin/bsOs.img /builds/bs-studios/bsos-cpp/build/kernel/bsOs.img
    - cp /builds/bs-studios/bsos-cpp/kernel/run.bat /builds/bs-studios/bsos-cpp/build/kernel/run.bat
    - cp /builds/bs-studios/bsos-cpp/OVMFbin/OVMF_CODE-pure-efi.fd /builds/bs-studios/bsos-cpp/build/OVMFbin/OVMF_CODE-pure-efi.fd
    - cp /builds/bs-studios/bsos-cpp/OVMFbin/OVMF_VARS-pure-efi.fd /builds/bs-studios/bsos-cpp/build/OVMFbin/OVMF_VARS-pure-efi.fd
